version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: build/docker/app/Dockerfile
    env_file:
      - build/docker/app/dev.env
      - build/docker/app/dev.env.private
    volumes:
      - .:/app
    ports:
      - 4444:3000
    command: ["bundle", "exec", "puma"]
    stdin_open: true
    tty: true

  webpacker:
    build:
      context: .
      dockerfile: build/docker/webpacker/Dockerfile
    env_file:
      - build/docker/webpacker/dev.env
    volumes:
      - .:/app
    ports:
      - 3035:3035
    command: ["./bin/webpack-dev-server"]
